# This is a basic workflow to help you get started with Actions

name: A TO A:GH_PAGES

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Build and Deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ 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 }}
          # 你要操作的目标仓库
          TARGET_REPO: zoeisgreat/zoeisgreat.github.io
          # 构建结果存储的分支
          TARGET_BRANCH: gh_pages
          # 要使用的构建命令
          BUILD_SCRIPT: yarn && yarn build
          # 构建结果存储目录
          BUILD_DIR: docs/.vuepress/dist/
